export const SHOW_CARTDROPDOWN = "SHOW_CARTDROPDOWN";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CLEAR_CHECKOUT_ITEM = "CLEAR_CHECKOUT_ITEM";
